/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppliedOffer {
  'originalAmount' : bigint,
  'finalAmount' : bigint,
  'offer' : PromotionalOffer,
  'discount' : bigint,
}
export type DiscountType = { 'percentage' : null } |
  { 'cashback' : null };
export type OfferId = bigint;
export type Operator = string;
export interface PromotionalOffer {
  'validityEnd' : Time,
  'title' : string,
  'active' : boolean,
  'discountValue' : bigint,
  'discountType' : DiscountType,
  'description' : string,
  'minRechargeAmount' : bigint,
  'validityStart' : Time,
  'maxDiscountCap' : [] | [bigint],
  'applicableOperators' : Array<Operator>,
  'offerId' : OfferId,
}
export type Time = bigint;
export interface _SERVICE {
  'applyOffer' : ActorMethod<[OfferId, bigint], [] | [AppliedOffer]>,
  'createOffer' : ActorMethod<
    [
      string,
      string,
      DiscountType,
      bigint,
      Array<Operator>,
      bigint,
      [] | [bigint],
      Time,
      Time,
    ],
    OfferId
  >,
  'getAllOffers' : ActorMethod<[], Array<PromotionalOffer>>,
  'getAvailableOffers' : ActorMethod<
    [Operator, bigint],
    Array<PromotionalOffer>
  >,
  'getOffer' : ActorMethod<[OfferId], [] | [PromotionalOffer]>,
  'toggleOfferStatus' : ActorMethod<[OfferId, boolean], boolean>,
  'updateOfferValidity' : ActorMethod<[OfferId, Time, Time], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];