/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OfferId = IDL.Nat;
export const Time = IDL.Int;
export const DiscountType = IDL.Variant({
  'percentage' : IDL.Null,
  'cashback' : IDL.Null,
});
export const Operator = IDL.Text;
export const PromotionalOffer = IDL.Record({
  'validityEnd' : Time,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'discountValue' : IDL.Nat,
  'discountType' : DiscountType,
  'description' : IDL.Text,
  'minRechargeAmount' : IDL.Nat,
  'validityStart' : Time,
  'maxDiscountCap' : IDL.Opt(IDL.Nat),
  'applicableOperators' : IDL.Vec(Operator),
  'offerId' : OfferId,
});
export const AppliedOffer = IDL.Record({
  'originalAmount' : IDL.Nat,
  'finalAmount' : IDL.Nat,
  'offer' : PromotionalOffer,
  'discount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'applyOffer' : IDL.Func(
      [OfferId, IDL.Nat],
      [IDL.Opt(AppliedOffer)],
      ['query'],
    ),
  'createOffer' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        DiscountType,
        IDL.Nat,
        IDL.Vec(Operator),
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        Time,
        Time,
      ],
      [OfferId],
      [],
    ),
  'getAllOffers' : IDL.Func([], [IDL.Vec(PromotionalOffer)], ['query']),
  'getAvailableOffers' : IDL.Func(
      [Operator, IDL.Nat],
      [IDL.Vec(PromotionalOffer)],
      ['query'],
    ),
  'getOffer' : IDL.Func([OfferId], [IDL.Opt(PromotionalOffer)], ['query']),
  'toggleOfferStatus' : IDL.Func([OfferId, IDL.Bool], [IDL.Bool], []),
  'updateOfferValidity' : IDL.Func([OfferId, Time, Time], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OfferId = IDL.Nat;
  const Time = IDL.Int;
  const DiscountType = IDL.Variant({
    'percentage' : IDL.Null,
    'cashback' : IDL.Null,
  });
  const Operator = IDL.Text;
  const PromotionalOffer = IDL.Record({
    'validityEnd' : Time,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'discountValue' : IDL.Nat,
    'discountType' : DiscountType,
    'description' : IDL.Text,
    'minRechargeAmount' : IDL.Nat,
    'validityStart' : Time,
    'maxDiscountCap' : IDL.Opt(IDL.Nat),
    'applicableOperators' : IDL.Vec(Operator),
    'offerId' : OfferId,
  });
  const AppliedOffer = IDL.Record({
    'originalAmount' : IDL.Nat,
    'finalAmount' : IDL.Nat,
    'offer' : PromotionalOffer,
    'discount' : IDL.Nat,
  });
  
  return IDL.Service({
    'applyOffer' : IDL.Func(
        [OfferId, IDL.Nat],
        [IDL.Opt(AppliedOffer)],
        ['query'],
      ),
    'createOffer' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          DiscountType,
          IDL.Nat,
          IDL.Vec(Operator),
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          Time,
          Time,
        ],
        [OfferId],
        [],
      ),
    'getAllOffers' : IDL.Func([], [IDL.Vec(PromotionalOffer)], ['query']),
    'getAvailableOffers' : IDL.Func(
        [Operator, IDL.Nat],
        [IDL.Vec(PromotionalOffer)],
        ['query'],
      ),
    'getOffer' : IDL.Func([OfferId], [IDL.Opt(PromotionalOffer)], ['query']),
    'toggleOfferStatus' : IDL.Func([OfferId, IDL.Bool], [IDL.Bool], []),
    'updateOfferValidity' : IDL.Func([OfferId, Time, Time], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };