/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface PromotionalOffer {
    validityEnd: Time;
    title: string;
    active: boolean;
    discountValue: bigint;
    discountType: DiscountType;
    description: string;
    minRechargeAmount: bigint;
    validityStart: Time;
    maxDiscountCap?: bigint;
    applicableOperators: Array<Operator>;
    offerId: OfferId;
}
export type Operator = string;
export type OfferId = bigint;
export interface AppliedOffer {
    originalAmount: bigint;
    finalAmount: bigint;
    offer: PromotionalOffer;
    discount: bigint;
}
export enum DiscountType {
    percentage = "percentage",
    cashback = "cashback"
}
export interface backendInterface {
    applyOffer(offerId: OfferId, rechargeAmount: bigint): Promise<AppliedOffer | null>;
    createOffer(title: string, description: string, discountType: DiscountType, discountValue: bigint, applicableOperators: Array<Operator>, minRechargeAmount: bigint, maxDiscountCap: bigint | null, validityStart: Time, validityEnd: Time): Promise<OfferId>;
    getAllOffers(): Promise<Array<PromotionalOffer>>;
    getAvailableOffers(operator: Operator, rechargeAmount: bigint): Promise<Array<PromotionalOffer>>;
    getOffer(offerId: OfferId): Promise<PromotionalOffer | null>;
    toggleOfferStatus(offerId: OfferId, isActive: boolean): Promise<boolean>;
    updateOfferValidity(offerId: OfferId, newStart: Time, newEnd: Time): Promise<boolean>;
}
import type { AppliedOffer as _AppliedOffer, DiscountType as _DiscountType, OfferId as _OfferId, Operator as _Operator, PromotionalOffer as _PromotionalOffer, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async applyOffer(arg0: OfferId, arg1: bigint): Promise<AppliedOffer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.applyOffer(arg0, arg1);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyOffer(arg0, arg1);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createOffer(arg0: string, arg1: string, arg2: DiscountType, arg3: bigint, arg4: Array<Operator>, arg5: bigint, arg6: bigint | null, arg7: Time, arg8: Time): Promise<OfferId> {
        if (this.processError) {
            try {
                const result = await this.actor.createOffer(arg0, arg1, to_candid_DiscountType_n9(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg6), arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOffer(arg0, arg1, to_candid_DiscountType_n9(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg6), arg7, arg8);
            return result;
        }
    }
    async getAllOffers(): Promise<Array<PromotionalOffer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOffers();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOffers();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableOffers(arg0: Operator, arg1: bigint): Promise<Array<PromotionalOffer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableOffers(arg0, arg1);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableOffers(arg0, arg1);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOffer(arg0: OfferId): Promise<PromotionalOffer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOffer(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOffer(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleOfferStatus(arg0: OfferId, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleOfferStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleOfferStatus(arg0, arg1);
            return result;
        }
    }
    async updateOfferValidity(arg0: OfferId, arg1: Time, arg2: Time): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOfferValidity(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOfferValidity(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_AppliedOffer_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppliedOffer): AppliedOffer {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_DiscountType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiscountType): DiscountType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PromotionalOffer_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PromotionalOffer): PromotionalOffer {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AppliedOffer]): AppliedOffer | null {
    return value.length === 0 ? null : from_candid_AppliedOffer_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PromotionalOffer]): PromotionalOffer | null {
    return value.length === 0 ? null : from_candid_PromotionalOffer_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    originalAmount: bigint;
    finalAmount: bigint;
    offer: _PromotionalOffer;
    discount: bigint;
}): {
    originalAmount: bigint;
    finalAmount: bigint;
    offer: PromotionalOffer;
    discount: bigint;
} {
    return {
        originalAmount: value.originalAmount,
        finalAmount: value.finalAmount,
        offer: from_candid_PromotionalOffer_n4(_uploadFile, _downloadFile, value.offer),
        discount: value.discount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    validityEnd: _Time;
    title: string;
    active: boolean;
    discountValue: bigint;
    discountType: _DiscountType;
    description: string;
    minRechargeAmount: bigint;
    validityStart: _Time;
    maxDiscountCap: [] | [bigint];
    applicableOperators: Array<_Operator>;
    offerId: _OfferId;
}): {
    validityEnd: Time;
    title: string;
    active: boolean;
    discountValue: bigint;
    discountType: DiscountType;
    description: string;
    minRechargeAmount: bigint;
    validityStart: Time;
    maxDiscountCap?: bigint;
    applicableOperators: Array<Operator>;
    offerId: OfferId;
} {
    return {
        validityEnd: value.validityEnd,
        title: value.title,
        active: value.active,
        discountValue: value.discountValue,
        discountType: from_candid_DiscountType_n6(_uploadFile, _downloadFile, value.discountType),
        description: value.description,
        minRechargeAmount: value.minRechargeAmount,
        validityStart: value.validityStart,
        maxDiscountCap: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.maxDiscountCap)),
        applicableOperators: value.applicableOperators,
        offerId: value.offerId
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    percentage: null;
} | {
    cashback: null;
}): DiscountType {
    return "percentage" in value ? DiscountType.percentage : "cashback" in value ? DiscountType.cashback : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PromotionalOffer>): Array<PromotionalOffer> {
    return value.map((x)=>from_candid_PromotionalOffer_n4(_uploadFile, _downloadFile, x));
}
function to_candid_DiscountType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DiscountType): _DiscountType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DiscountType): {
    percentage: null;
} | {
    cashback: null;
} {
    return value == DiscountType.percentage ? {
        percentage: null
    } : value == DiscountType.cashback ? {
        cashback: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
